name: All Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          # Change this to be your CI task/script
          runCmd: python -m cin_validator test